### ISSUE TITLE
Opdatering af listen, grundet virksomheds opkøb i perioden 2015-2018

### ISSUE THREAD

**Issue by netravnen** [emilstahl/ipv6#17]
@emilstahl bør følgende items ikke opdateres, grundet de begge er en del af GlobalConnect, nu?

![image](https://user-images.githubusercontent.com/1938389/68551059-d2b7e680-0400-11ea-8653-9a1086245d83.png)

![image](https://user-images.githubusercontent.com/1938389/68551068-e2372f80-0400-11ea-922c-952bf0e225a9.png)

**Comment by eKristensen** [comment]
Jeg er ikke andet hos nianet eller global connect, så der kan jeg desværre ikke udtale mig om.

**Comment by netravnen** [comment]
@eKristensen tænker jeg kan. Grundet jeg var ansat hos dem indtil Q3 tidl. i år. Der også en lang række presse meddelelser og CVR registret er blevet opdaret. F.eks. er det tidl. Nianet A/S nu blevet omdøbt til GlobalConnect NN A/S.

**Comment by emilstahl** [comment]
Du har tagged den forkerte Emil. Jeg kender godt til opkøbet, men har ikke fået opdateret data. Det skal jeg nok få gjort :)

**Comment by netravnen** [comment]
> Du har tagged den forkerte Emil. Jeg kender godt til opkøbet, men har ikke fået opdateret data. Det skal jeg nok få gjort :)

Kan jeg da godt se. Hvorfor jeg tagged den forkerte person. Ved jeg dog ik'.'

**Comment by netravnen** [comment]
#18 åbnet

**Comment by emilstahl** [comment]
Merged. Tak
