### ISSUE TITLE
Tilføj data for privat/erhverv

### ISSUE THREAD

**Issue by dvaeversted** [emilstahl/ipv6#2]
Mange a ISP'erne understøtter IPv6 på erhvervsforbindelser.

Hvis vi tilføjer et flag til hhv. private og bussiness, kan vi lave noget fancy javascript filtrering osv...

**Comment by emilstahl** [comment]
God idé, men hvad skal vi kalde det?

`private` og `business` giver sig selv, men hvad ska vi kalde det, hvis en ISP leverer til begge dele? Intet flag = begge dele?

**Comment by dvaeversted** [comment]
Jeg ville bare tilføje 2 boolean flag, med de navne.
Der er jo også nogle ISP'er, f.eks. Kviknet som ikke lige umiddelbart har nogle erhvervs produkter.
