### ISSUE TITLE
Flyt IPv6 detektion til javascript

### ISSUE THREAD

**Issue by dvaeversted** [emilstahl/ipv6#5]
Lav IPv6 ISP detection asynkron med noget javascript, så det hele ikke breaker bare fordi ip-api.com er nede.

**Comment by emilstahl** [comment]
ip-api.com der i dag bruges server-side har [Callback (JSONP) support](http://ip-api.com/docs/api:json#callback_jsonp). 

Vi skal i hvert fald ikke bruge ipinfo.io 💩 
>We support looking up data for IPv6 addresses, but we don't support IPv6 connections due to us using Amazon AWS. As soon as Amazon add support for IPv6 we'll support it!
