### ISSUE TITLE
Stofa don't offer ipv6 according to helpdesk

### ISSUE THREAD

**Issue by 0xUnicorn** [emilstahl/ipv6#62]
I wrote a message to their helpdesk asking for an ipv6 prefix and was told they do not offer any kind of ipv6.

**Comment by emilstahl** [comment]
@0xUnicorn It may depend on the type of internet connection and where in Denmark you are located. Stofa certainly provides IPv6 on certain connections.

**Comment by 0xUnicorn** [comment]
> @0xUnicorn It may depend on the type of internet connection and where in Denmark you are located. Stofa certainly provides IPv6 on certain connections.

Interesting. Would you be able to provide more info on which connections or locations is required to your knowledge?

**Comment by emilstahl** [comment]
@0xUnicorn IPv6 should be supported on fiber in most of Denmark (there may be a few local discrepancies). There is no IPv6 support on coax, and I don't think that's on xDSL either.

Report from an employee in July:
> We have now for a while enabled some "ordinary" consumers with IPv6 as default.

Which connection type are you on (fiber, coax, xDSL) and in which part of Denmark are you located?

**Comment by 0xUnicorn** [comment]
@emilstahl - Thanks for the ellaboration. I'm on coax, so makes sense.

May I suggest to add this info to the site?

**Comment by emilstahl** [comment]
@0xUnicorn Of course, done. Thank you for the feedback :)

**Comment by debdrup** [comment]
Would it be an idea to add a hint for what/who to talk to? I talked to support, and they said they don't provide it, even on fiber.

**Comment by AlbertSPedersen** [comment]
I'm on a fiber connection from Stofa ("medarbejderbredbånd"). I just spoke to an employee who claims Stofa does not offer IPv6 except to select business customers.

> Report from an employee in July:
> 
> > We have now for a while enabled some "ordinary" consumers with IPv6 as default.

@emilstahl could you share the source or let us know who contact?

@debdrup did you figure something out?
