### ISSUE TITLE
Nef arbejder på IPv6?

### ISSUE THREAD

**Issue by victorpahuus** [emilstahl/ipv6#70]
Jeg faldt tilfældigvis over Nef's "service brev", omkring ændringer for deres netværk.
Fra april vil de foretage ændringer, som gør de på sigt kan tilbyde IPv6.

> Samtidig forbereder vi netværket til senere at kunne tilbyde dig IPv6. Senere kommer der også IPv6 med DHCPv6-PD, så dit interne netværk kan få IPv6-adresser.

https://nef.dk/kundeservice/fibernet-aendringer-2023/

**Comment by amatzen** [comment]
Tak for dit bidrag @victorpahuus ! 😄
