### ISSUE TITLE
Nedlæg Gigabit/Wizer nu de sidste kunder er meldt "solgt" til BOLIGNET

### ISSUE THREAD

**Issue by netravnen** [emilstahl/ipv6#90]
https://wizer.dk/bolignet/

> Du overgår til BOLIG•NET
> Vi er rigtig glade for at fortælle at vores resterende boligforening samt privatkunder overgår til BOLIG·NET.
> 
> BOLIG·NET er kendt for sin stabile fibernet forbindelse og høje kundetilfredshed. Vi er sikre på, at det bliver en glædelig fornøjelse for alle! Du har modtaget en informations mail, som beskriver, hvordan du skal forholde dig til overdragelsen, samt hvad den helt konkret betyder for dig.

**Comment by netravnen** [comment]
https://l.bolignet.dk/privat/wizer-ftth

> BOLIG·NET byder
> hjerteligt velkommen
> Den 15. august 2023 overtager BOLIG·NET driften og kundesupporten af 2.500 fiberkunder fra Wizer.
> 
> "Vi byder vores nye kunder hjertelig velkommen til BOLIG∙NET-familien. Vi vil selvføgelig sørge for en god kommunikation, samt sikre en gnidningsfri overgang til BOLIG∙NET og give vores nye kunder en pålidelig og hurtig internetforbindelse samt en førsteklasses kundeserviceoplevelse. Vi er sikre på, at vores ekspertise og dedikation vil give vores nye kunder en internetoplevelse, der overgår deres forventninger", udtaler direktør Anders Kjærgaard Jørgensen.
>

**Comment by netravnen** [comment]
23-11-2023 ITWATCH

> Fiberselskabet Wizer er gået konkurs
> 
> Fiberselskabet Wizer er gået konkurs, skriver Computerworld på baggrund af en konkursbegæring i Skifteretten i Kolding . ... Men nu opgiver selskabet altså helt. ”Det betyder, at den forbindelse vi servicerer for Wizer, ikke længere betales, hvorfor udgangspunktet er, at forbindelsen skal lukkes,” skriver Bolig i en mail til selskabets kunder, der stadig er aktive på Wizers forbindelse.

https://itwatch.dk/ITNyt/Brancher/tele/article16629395.ece

----

24-11-2023 ITWATCH

> Globalconnect må sætte projekter på pause efter Wizer-konkurs
> 
> Transaktionen skete som led i forsøg på at gøre Wizer rentabel. ... Wizers fibernetværk dækker Nordsjælland og Storkøbenhavn.

https://itwatch.dk/ITNyt/Brancher/leverandoerer/article16631261.ece

**Comment by emilstahl** [comment]
#102 merged, løst. Tak :)
