### ISSUE TITLE
Fjern Eniig der er blevet til Stofa

### ISSUE THREAD

**Issue by netravnen** [emilstahl/ipv6#91]
Fjern Eniig.dk fra oversigten. Nu de har annonceret det er blevet til Stofa. https://eniig.dk/

![image](https://github.com/emilstahl/ipv6/assets/1938389/2cac40fc-020d-45ed-a9e2-e5feb53d9f5c)

**Comment by amatzen** [comment]
Udover det her, så har Stofa også annonceret de bliver til Norlys.

Det er glædeligt, at de nu har valgt en uniform løsning.

**Comment by netravnen** [comment]
Closed via #93 #94 #95
