### ISSUE TITLE
Norlys tilbyder ikke IPv6 på fiber.

### ISSUE THREAD

**Issue by Scavy** [emilstahl/ipv6#96]
Jeg har været i kontakt med kundesupport hos Norlys, og fået den melding at det ikke er noget de understøtter på fiber.
![billede](https://github.com/emilstahl/ipv6/assets/4381602/c26d9c3e-86f9-43f2-8b04-3dc57248af88)

**Comment by emilstahl** [comment]
Det er lidt en duplicate af #83. Det er lidt forskelligt om det er muligt eller ej.
