### ISSUE TITLE
Svar fra Waoo (tidl. Fibia?)

### ISSUE THREAD

**Issue by DarkFox** [emilstahl/ipv6#99]
Spørger man Waoo's chatbot om IPv6, får man følgende svar:

Conversation
------------

Created:    2023-11-02T18:21:34.064140+01:00
Downloaded: 2023-11-02T18:22:21.337546+01:00
Source: https://www.waoo.dk/

Number of requests:    2
Number of responses:   3

Waoo:
    - "Hej! Jeg er Waoos chatbot, og jeg er klar til at hjælpe dig 😊Beskriv med få ord hvordan jeg kan hjælpe dig."
    - "Du bør ikke dele personfølsomme oplysninger i chatten, du kan læse mere om vores persondatapolitik"
    - Options: "Persondatapolitik", "Åbningstider"
    - "Find din lokale Waoo Partner her👇"
    - Options: "Waoo Partner"

You:
    - "Understøtter min fiberforbindelse fra Waoo IPv6?"

Waoo:
    - "Jeg er ikke sikker på, om jeg forstod det, du spurgte om, men jeg kan hjælpe dig med:"
    - Options: "IPV6", "Waoo Fiber", "Hjælp til internet"

You:
    - "IPV6"

Waoo:
    - "Desværre, så tilbyder vi ikke IPV6 på vores forbindelser.<br>Vi har IPV4 adresser og tilbyder 3 forskellige typer 😊"
    - "<ul> 
 <li>En Privat dynamisk IP </li> 
 <li>En Offentlig dynamisk IP </li> 
 <li>En Fast IP adresse </li> 
</ul>"
    - "Ønsker du mere information? "
    - Options: "Offenligt IP", "Fast IP"

**Comment by czingenberg** [comment]
Yep.

Fibia understøtter desværre ikke IPv6 endnu -.-

**Comment by netravnen** [comment]
Øv øv øv. 😭

Min opfattelse er det (ofte) er BSS (Business Support Systems) kombineret med videns-niveauet i kundevendte service funktioner der er den tunge løftestang at bringe op. Nogle virksomheder kan vi allerede i dag se har langt til 💯
